name: TruffleHog Scan

on:
  push:
    branches:
      - master
      - layout
  pull_request:

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run TruffleHog
        uses: edplato/trufflehog@master